import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";
import Web3Provider from "@/providers/Web3Provider";
import "./globals.css";
import "@mantine/core/styles.css";
import "@rainbow-me/rainbowkit/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web3 Campus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body className={inter.className}>
        <Web3Provider>
          <MantineProvider>{children}</MantineProvider>
        </Web3Provider>
          <script src="https://cdn.tailwindcss.com"></script>
      </body>
    </html>
  );
}
